# Generated by Django 4.0.4 on 2022-05-28 16:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geraete_name', models.CharField(default=None, max_length=30)),
                ('geraete_status', models.CharField(default=None, max_length=10)),
                ('geraete_kosten', models.IntegerField(default=None)),
                ('geraete_hersteller', models.CharField(default=None, max_length=10)),
                ('geraete_anschaffungsdatum', models.DateField()),
                ('geraete_garantiedauer_start', models.TimeField()),
                ('geraete_garantiedauer_ende', models.TimeField()),
                ('geraete_seriennummer', models.CharField(default=None, max_length=50)),
                ('geraete_garantie_information', models.CharField(default=None, max_length=50)),
                ('geraete_information', models.CharField(default=None, max_length=100)),
            ],
            options={
                'verbose_name': 'Gerät',
                'verbose_name_plural': 'Geräte',
            },
        ),
        migrations.CreateModel(
            name='DeviceClasses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.ImageField(default=None, upload_to='static/images')),
            ],
            options={
                'verbose_name': 'Geräte-Klasse',
                'verbose_name_plural': 'Geräte-Klassen',
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=10)),
                ('bauabschnitt', models.CharField(choices=[('1', '1. Bauabschnitt'), ('2', '2. Bauabschnitt')], max_length=1)),
                ('etage', models.CharField(choices=[('-1', 'Kellergeschoss'), ('0', 'Erdgeschoss'), ('1', '1. Obergeschoss'), ('2', '2. Obergeschoss')], max_length=2)),
            ],
            options={
                'verbose_name': 'Raum',
                'verbose_name_plural': 'Räume',
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_header', models.CharField(default=None, max_length=30)),
                ('ticket_message', models.CharField(default=None, max_length=300)),
            ],
            options={
                'verbose_name': 'Ticket',
                'verbose_name_plural': 'Tickets',
            },
        ),
        migrations.CreateModel(
            name='MyUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('person_id', models.CharField(max_length=10, unique=True, verbose_name='itslearning – Person ID')),
                ('username', models.CharField(max_length=25, unique=True, verbose_name='Benutzername')),
                ('first_name', models.CharField(max_length=25, verbose_name='Vorname')),
                ('last_name', models.CharField(max_length=25, verbose_name='Nachname')),
                ('language', models.CharField(default='de-DE', max_length=10, verbose_name='Sprache')),
                ('profile_image_url', models.CharField(blank=True, max_length=100, null=True, verbose_name='Profilbild-URL')),
                ('use_12_hour_time_format', models.BooleanField(default=False, verbose_name='Zwölf-Stunden Zeitformat')),
                ('allow_auto_role', models.BooleanField(default=True, verbose_name='Automatische Rollen via itslearning')),
                ('is_guest', models.BooleanField(default=False, verbose_name='Ist Gast')),
                ('is_staff', models.BooleanField(default=False, verbose_name='Ist Lehrer')),
                ('is_admin', models.BooleanField(default=False, verbose_name='Ist Admin')),
                ('is_superuser', models.BooleanField(default=False, verbose_name='Ist System-Admin')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ist Aktiv')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
        ),
    ]
